/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package nonamespace;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class nonsenseConstants {

  public static final double PI = 3.14159;

}
