/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nonsenseproject;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.thrift.TException;
// import code generated by Apache Thrift compiler
import nonsenseproject.*;

/**
 *
 * @author QuyTN
 */
public class NonsenseHandler implements NonsenseService.Iface {
    
    public NonsenseHandler() {
        
    }
    
    @Override
    public void log(String filename) {
        System.out.println("Write log to " + filename);
    } ;
    
    @Override
    public returnval upload(file upfile) {
        FileOutputStream out;
        try {
            out = new FileOutputStream(upfile.getName());
            out.getChannel().write(upfile.bufferForBuf());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NonsenseHandler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NonsenseHandler.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("File " + upfile.getName() + " received!");
        return new returnval(0, "test");
    } 

    @Override
    public answer ask(String question) {
        answer ans = new answer(0, " ", "This is a nonsense service");
        System.out.println("Receive question: " + question);
        return ans;
    }
    
    @Override
    public void endsession() {
        System.out.println("End session!");
    }
    
}
